global using System.Globalization;
global using System.Diagnostics.CodeAnalysis;
global using System.IO.Compression;
global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using System.Xml.Linq;
global using Morph;
global using ProjectFilesGenerator;
global using SixLabors.ImageSharp;
global using SixLabors.ImageSharp.Metadata.Profiles.Exif;
global using SixLabors.ImageSharp.PixelFormats;
global using TUnit.Core.Interfaces;
global using static ExportTestBuilders;
