<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>CS0618;CS1591;CS1572;NU1902</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Morph\Morph.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="SixLabors.ImageSharp.Drawing" />
    <PackageReference Include="SixLabors.Fonts" />
  </ItemGroup>

</Project>
