#!/usr/bin/env bash
#
# In-container orchestrator: run the build/tests against a container-local copy of the
# working tree instead of the bind-mounted one, then sync back whatever the run changed.
#
# WHY
#   On a Windows host, Docker Desktop exposes the working tree over 9p/drvfs. That mount is
#   dramatically slower than the container's own ext4 layer — measured on this repo: reading
#   300 baseline PNGs took 1.54s from the mount versus 0.018s locally (~85x), and a *no-op*
#   MSBuild up-to-date check cost ~21s (~38s cold) with almost all of it in I/O wait. The
#   suite reads ~5,900 files / ~894MB per run across two rendering backends, so the mount
#   dominates: the full suite measured 4m34s on the mount versus 2m15s run locally.
#
#   Copying in costs ~24s and the build then lands on ext4 too (no separate artifacts-path
#   redirection needed), so the round trip still wins by roughly two minutes.
#
#   On a Linux host the bind mount is native and this indirection buys nothing — set
#   MORPH_DIRECT=1 to skip it (scripts/test.sh also does that automatically for `bash`).
#
# SYNCING BACK
#   The suite writes files the host must see, and not only the obvious ones:
#     - *.received.* Verify snapshots      (scripts/regenerate-baselines.sh promotes these
#                                           on the HOST, and CI uploads them on failure)
#     - compare.md / compare-all-images.md (TRACKED files regenerated by
#                                           ScenarioMarkdownGenerator during the run)
#     - nugets/*.nupkg                     (CI uploads these on success)
#     - TestResults/                       (the HTML report)
#   Rather than enumerate that list and risk missing the next one, everything modified after
#   a marker file is copied back. bin/obj are excluded as pure build output — except any
#   TestResults directory inside them, which is copied wholesale.
#
#   Deletions are not detected by an mtime sweep, which matters for exactly one case: Verify
#   removes a .received.* file when its test starts passing. Left alone, a stale copy would
#   linger on the host and corrupt regenerate-baselines.sh's promotion count. So host
#   .received.* files are cleared before the sync and replaced with the container's set —
#   safe because they are gitignored build artifacts.

set -uo pipefail

src=/src
work=/work
marker=/tmp/run-start

echo ">>> Copying the working tree to container-local disk (bypassing the 9p bind mount)" >&2
mkdir -p "$work"
tar cf - \
    --exclude=./.git \
    --exclude=./.nuget-cache \
    --exclude=bin \
    --exclude=obj \
    -C "$src" . | tar xf - -C "$work"

# Created after extraction so the copy's own preserved mtimes never look "modified".
touch "$marker"

cd "$work"

if [[ $# -eq 0 ]]; then
    dotnet run --project src/Tests --configuration Release
else
    "$@"
fi
status=$?

# Sync back even when the run failed — that is precisely when .received.* files matter.
echo ">>> Syncing changed files back to the host" >&2

# Verify deletes a .received.* the moment its test passes; mirror that by clearing the host
# set first, so what remains is exactly what this run produced.
find "$src/src/Tests" -type f -name '*.received.*' \
    -not -path '*/bin/*' -not -path '*/obj/*' -delete 2>/dev/null

changed=/tmp/changed.txt
find . -type f -newer "$marker" \
    -not -path './.git/*' \
    -not -path '*/bin/*' \
    -not -path '*/obj/*' \
    > "$changed"

# TestResults land under bin/, which the sweep above excludes as build output.
find . -type d -name TestResults -newer "$marker" -exec find {} -type f \; >> "$changed" 2>/dev/null

if [[ -s "$changed" ]]; then
    echo ">>> $(wc -l < "$changed") changed file(s)" >&2
    tar cf - -T "$changed" | tar xf - -C "$src"
else
    echo ">>> No files changed" >&2
fi

exit $status
