<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>CS0618;CS1591;CS1572</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Morph\Morph.csproj" />
    <PackageReference Include="ProjectDefaults" PrivateAssets="all" />
    <PackageReference Include="SkiaSharp" />
    <PackageReference Include="Svg.Skia" />
  </ItemGroup>

</Project>
