<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <Version>0.9.0</Version>
    <NoWarn>NU1608</NoWarn>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <LangVersion>preview</LangVersion>
    <Description>Convert docx to png</Description>
    <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
    <ImplicitUsings>enable</ImplicitUsings>
    <ResolveAssemblyReferencesSilent>true</ResolveAssemblyReferencesSilent>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
    <SixLaborsLicenseFile>$(MSBuildThisFileDirectory)sixlabors.lic</SixLaborsLicenseFile>
  </PropertyGroup>
</Project>
